name: Matrix demo 
on: push
jobs: 
  build: 
    strategy:
      matrix:
        node-version: [14,16,18] ## The key name here is not reserved so you can name it whatever
        os: [ubuntu-latest, windows-latest] ## The key name here is not reserved so you can name it whatever
        include: ## this key is reserved by GHA, means the combination below is included in the workflow
          - node-version: 20
            os: ubuntu-latest
        exclude: ## this key is reserved by GHA, means the combination below is excluded in the workflow
          - node-version: 14
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci 
      - name: Build project
        run: npm run build