name: Reusable deploy
on: 
  workflow_call: 
    inputs: ## Providing inputs for your reusable workflow
      artifact-name:
        description: The name of the deployable artifact files 
        required: false ## set to false, workflow can be called without providing a value
                        ## set to true, the value is needed
        default: dist   ## if we didnt get any value, the default value is used
        type: string
    ouputs: 
      result: 
        description: the result of the deployment opertion
        value: ${{ jobs.deploy.outputs.outcome }}
    #secrets:
      #some-secrets:
        #required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}

    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with: 
          name: ${{ inputs.artifact-name }}
          ## Dynamic because we want to get the artifiact name from the other workflow
          ## reusable workflow is like a function that can be called by other workflow
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying and Uploading..."
      - name: Set result output
        id: set-result
        run: echo "step-result=sucess" >> $GITHUB_OUPUT
        ## String sucess will be stored on the step-result